### ISSUE TITLE
Update Backup/Restore in Manifest

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/hello-world-wrapper#8]
Reported by: @chrisguida

**Comment by elvece** [comment]
Fixed [here](https://github.com/Start9Labs/hello-world-wrapper/commit/67cbdb8bc71822a34f455b34a5bc61d565bcc7aa#diff-d865b06b497efc8c56c63e5bedfc86f6da6a005cdb7d30e3702286f3d918aaa6R168-R198)
